package com.namma_shaale.inventory.util

import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import javax.inject.Inject

class ReportBuilder @Inject constructor() {
    fun buildSummaryReport(
        totalAssets: Int,
        greenCount: Int,
        yellowCount: Int,
        redCount: Int,
        pendingRepairs: Int
    ): String {
        val healthPercent = if (totalAssets > 0) (greenCount * 100) / totalAssets else 0
        val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        val timestamp = sdf.format(Calendar.getInstance().time)

        return """
            ═══════════════════════════════════════════════════════════
            NAMMA-SHAALE INVENTORY REPORT
            Generated: $timestamp
            ═══════════════════════════════════════════════════════════

            ASSET HEALTH SUMMARY
            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            Total Assets: $totalAssets
            ✓ Working (Green): $greenCount (${if (totalAssets > 0) (greenCount * 100) / totalAssets else 0}%)
            ⚠ Needs Repair (Yellow): $yellowCount (${if (totalAssets > 0) (yellowCount * 100) / totalAssets else 0}%)
            ✗ Broken/Lost (Red): $redCount (${if (totalAssets > 0) (redCount * 100) / totalAssets else 0}%)

            Overall Health: $healthPercent%
            Pending SDMC Repairs: $pendingRepairs

            ═══════════════════════════════════════════════════════════
            Generated by Namma-Shaale Inventory
        """.trimIndent()
    }
}
